[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
clap = { version = "4.4.8", features = ["cargo", "derive", "env", "string", "unicode"] }
error-stack = "0.4.1"
fast_log = { version = "1.6.10", features = ["zip"] }
log = { version = "0.4.20", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
bimap = { version = "0.6.3", features = ["serde"] }
game2 = { path = ".." }
server = { path = "../server" }
rayon = "1.8.0"
block-mesh = "0.2.0"
bitvec = { version = "1.0.1", features = ["serde"] }
bevy_rapier3d = { version = "0.23.0", features = ["wasm-bindgen", "serde", "parallel", "debug-render"] }
serde-big-array = "0.5.1"
slab = { version = "0.4.9", features = ["serde"] }
serde_json = "1.0.108"
crunch = "0.5.3"
wtransport = "0.1.10"

[profile.dev]
opt-level = 1

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
lto = true

[profile.dev.package."*"]
opt-level = 3
