[package]
name = "game2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "1.3.3", features = ["i128"] }
bytemuck = { version = "1.14.0", features = ["aarch64_simd", "wasm_simd"] }
enumset = { version = "1.1.3", features = ["std", "serde", "alloc"] }
itertools = "0.12.0"
lz4_flex = "0.11.1"
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive", "rc", "alloc"] }
serde-big-array = "0.5.1"
slab = { version = "0.4.9", features = ["serde"] }
smallvec = { version = "1.11.2", features = ["serde", "union", "const_new", "write"] }
structdoc = "0.1.4"
unstructured = "0.5.1"
zstd = { version = "0.13.0", features = ["wasm", "bindgen"] }

[dependencies.bevy]
version = "0.12.0"
default-features = false

[workspace]
members = [
    "client",
    "server"
]

[profile.release]
codegen-units = 1
