[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive", "alloc", "rc"] }
game2 = { path = ".." }
uuid = { version = "1.6.1", features = ["v4", "serde", "wasm-bindgen", "getrandom"] }
deno_core = "0.239.0"
tokio = { version = "1.34.0", features = ["full"] }
bincode = { version = "1.3.3", features = ["i128"] }
async-trait = "0.1.75"
lz4_flex = "0.11.1"
bimap = { version = "0.6.3", features = ["serde"] }
zstd = { version = "0.13.0", features = ["wasm", "bindgen"] }
moka = { version = "0.12.1", features = ["log", "future", "async-lock", "async-trait", "js"] }
rayon = "1.8.0"
rand = { version = "0.8.5", features = ["log", "serde"] }
opensimplex2 = "1.0.1"
wtransport = "0.1.10"

[dependencies.bevy]
version = "0.12.0"
default-features = false
features = [
    "android_shared_stdcxx",
    "multi-threaded",
    "async-io"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
